name: Test JAVA project on different OS

on:
  pull_request:
    branches:
      - master
      - develop
      - gitactions
      - final
  push:
    branches:
      - master
      - develop
      - gitactions
      - final

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Java JDK on ${{ matrix.os }}
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Build with Maven on ${{ matrix.os }}
        run: mvn package